/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/php_opcode.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/php_opcode.pb-c.h"
void   zval_null__init
                     (ZvalNull         *message)
{
  static const ZvalNull init_value = ZVAL_NULL__INIT;
  *message = init_value;
}
size_t zval_null__get_packed_size
                     (const ZvalNull *message)
{
  assert(message->base.descriptor == &zval_null__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_null__pack
                     (const ZvalNull *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_null__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_null__pack_to_buffer
                     (const ZvalNull *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_null__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalNull *
       zval_null__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalNull *)
     protobuf_c_message_unpack (&zval_null__descriptor,
                                allocator, len, data);
}
void   zval_null__free_unpacked
                     (ZvalNull *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_null__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_long__init
                     (ZvalLong         *message)
{
  static const ZvalLong init_value = ZVAL_LONG__INIT;
  *message = init_value;
}
size_t zval_long__get_packed_size
                     (const ZvalLong *message)
{
  assert(message->base.descriptor == &zval_long__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_long__pack
                     (const ZvalLong *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_long__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_long__pack_to_buffer
                     (const ZvalLong *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_long__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalLong *
       zval_long__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalLong *)
     protobuf_c_message_unpack (&zval_long__descriptor,
                                allocator, len, data);
}
void   zval_long__free_unpacked
                     (ZvalLong *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_long__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_double__init
                     (ZvalDouble         *message)
{
  static const ZvalDouble init_value = ZVAL_DOUBLE__INIT;
  *message = init_value;
}
size_t zval_double__get_packed_size
                     (const ZvalDouble *message)
{
  assert(message->base.descriptor == &zval_double__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_double__pack
                     (const ZvalDouble *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_double__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_double__pack_to_buffer
                     (const ZvalDouble *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_double__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalDouble *
       zval_double__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalDouble *)
     protobuf_c_message_unpack (&zval_double__descriptor,
                                allocator, len, data);
}
void   zval_double__free_unpacked
                     (ZvalDouble *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_double__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_string__init
                     (ZvalString         *message)
{
  static const ZvalString init_value = ZVAL_STRING__INIT;
  *message = init_value;
}
size_t zval_string__get_packed_size
                     (const ZvalString *message)
{
  assert(message->base.descriptor == &zval_string__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_string__pack
                     (const ZvalString *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_string__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_string__pack_to_buffer
                     (const ZvalString *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_string__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalString *
       zval_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalString *)
     protobuf_c_message_unpack (&zval_string__descriptor,
                                allocator, len, data);
}
void   zval_string__free_unpacked
                     (ZvalString *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_string__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_array__init
                     (ZvalArray         *message)
{
  static const ZvalArray init_value = ZVAL_ARRAY__INIT;
  *message = init_value;
}
size_t zval_array__get_packed_size
                     (const ZvalArray *message)
{
  assert(message->base.descriptor == &zval_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_array__pack
                     (const ZvalArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_array__pack_to_buffer
                     (const ZvalArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalArray *
       zval_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalArray *)
     protobuf_c_message_unpack (&zval_array__descriptor,
                                allocator, len, data);
}
void   zval_array__free_unpacked
                     (ZvalArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_object__init
                     (ZvalObject         *message)
{
  static const ZvalObject init_value = ZVAL_OBJECT__INIT;
  *message = init_value;
}
size_t zval_object__get_packed_size
                     (const ZvalObject *message)
{
  assert(message->base.descriptor == &zval_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_object__pack
                     (const ZvalObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_object__pack_to_buffer
                     (const ZvalObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalObject *
       zval_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalObject *)
     protobuf_c_message_unpack (&zval_object__descriptor,
                                allocator, len, data);
}
void   zval_object__free_unpacked
                     (ZvalObject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_bool__init
                     (ZvalBool         *message)
{
  static const ZvalBool init_value = ZVAL_BOOL__INIT;
  *message = init_value;
}
size_t zval_bool__get_packed_size
                     (const ZvalBool *message)
{
  assert(message->base.descriptor == &zval_bool__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_bool__pack
                     (const ZvalBool *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_bool__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_bool__pack_to_buffer
                     (const ZvalBool *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_bool__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalBool *
       zval_bool__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalBool *)
     protobuf_c_message_unpack (&zval_bool__descriptor,
                                allocator, len, data);
}
void   zval_bool__free_unpacked
                     (ZvalBool *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_bool__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_resource__init
                     (ZvalResource         *message)
{
  static const ZvalResource init_value = ZVAL_RESOURCE__INIT;
  *message = init_value;
}
size_t zval_resource__get_packed_size
                     (const ZvalResource *message)
{
  assert(message->base.descriptor == &zval_resource__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_resource__pack
                     (const ZvalResource *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_resource__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_resource__pack_to_buffer
                     (const ZvalResource *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_resource__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalResource *
       zval_resource__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalResource *)
     protobuf_c_message_unpack (&zval_resource__descriptor,
                                allocator, len, data);
}
void   zval_resource__free_unpacked
                     (ZvalResource *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_resource__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_const__init
                     (ZvalConst         *message)
{
  static const ZvalConst init_value = ZVAL_CONST__INIT;
  *message = init_value;
}
size_t zval_const__get_packed_size
                     (const ZvalConst *message)
{
  assert(message->base.descriptor == &zval_const__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_const__pack
                     (const ZvalConst *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_const__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_const__pack_to_buffer
                     (const ZvalConst *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_const__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalConst *
       zval_const__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalConst *)
     protobuf_c_message_unpack (&zval_const__descriptor,
                                allocator, len, data);
}
void   zval_const__free_unpacked
                     (ZvalConst *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_const__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval_const_ast__init
                     (ZvalConstAst         *message)
{
  static const ZvalConstAst init_value = ZVAL_CONST_AST__INIT;
  *message = init_value;
}
size_t zval_const_ast__get_packed_size
                     (const ZvalConstAst *message)
{
  assert(message->base.descriptor == &zval_const_ast__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval_const_ast__pack
                     (const ZvalConstAst *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval_const_ast__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval_const_ast__pack_to_buffer
                     (const ZvalConstAst *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval_const_ast__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ZvalConstAst *
       zval_const_ast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ZvalConstAst *)
     protobuf_c_message_unpack (&zval_const_ast__descriptor,
                                allocator, len, data);
}
void   zval_const_ast__free_unpacked
                     (ZvalConstAst *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval_const_ast__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   zval__init
                     (Zval         *message)
{
  static const Zval init_value = ZVAL__INIT;
  *message = init_value;
}
size_t zval__get_packed_size
                     (const Zval *message)
{
  assert(message->base.descriptor == &zval__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t zval__pack
                     (const Zval *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &zval__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t zval__pack_to_buffer
                     (const Zval *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &zval__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Zval *
       zval__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Zval *)
     protobuf_c_message_unpack (&zval__descriptor,
                                allocator, len, data);
}
void   zval__free_unpacked
                     (Zval *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &zval__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   znode__init
                     (Znode         *message)
{
  static const Znode init_value = ZNODE__INIT;
  *message = init_value;
}
size_t znode__get_packed_size
                     (const Znode *message)
{
  assert(message->base.descriptor == &znode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t znode__pack
                     (const Znode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &znode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t znode__pack_to_buffer
                     (const Znode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &znode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Znode *
       znode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Znode *)
     protobuf_c_message_unpack (&znode__descriptor,
                                allocator, len, data);
}
void   znode__free_unpacked
                     (Znode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &znode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   opcode_list__init
                     (OpcodeList         *message)
{
  static const OpcodeList init_value = OPCODE_LIST__INIT;
  *message = init_value;
}
size_t opcode_list__get_packed_size
                     (const OpcodeList *message)
{
  assert(message->base.descriptor == &opcode_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opcode_list__pack
                     (const OpcodeList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opcode_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opcode_list__pack_to_buffer
                     (const OpcodeList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opcode_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpcodeList *
       opcode_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpcodeList *)
     protobuf_c_message_unpack (&opcode_list__descriptor,
                                allocator, len, data);
}
void   opcode_list__free_unpacked
                     (OpcodeList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opcode_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   opcode__init
                     (Opcode         *message)
{
  static const Opcode init_value = OPCODE__INIT;
  *message = init_value;
}
size_t opcode__get_packed_size
                     (const Opcode *message)
{
  assert(message->base.descriptor == &opcode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opcode__pack
                     (const Opcode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opcode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opcode__pack_to_buffer
                     (const Opcode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opcode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Opcode *
       opcode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Opcode *)
     protobuf_c_message_unpack (&opcode__descriptor,
                                allocator, len, data);
}
void   opcode__free_unpacked
                     (Opcode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opcode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define zval_null__field_descriptors NULL
#define zval_null__field_indices_by_name NULL
#define zval_null__number_ranges NULL
const ProtobufCMessageDescriptor zval_null__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalNull",
  "ZvalNull",
  "ZvalNull",
  "",
  sizeof(ZvalNull),
  0,
  zval_null__field_descriptors,
  zval_null__field_indices_by_name,
  0,  zval_null__number_ranges,
  (ProtobufCMessageInit) zval_null__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zval_long__field_descriptors[1] =
{
  {
    "lval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(ZvalLong, lval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zval_long__field_indices_by_name[] = {
  0,   /* field[0] = lval */
};
static const ProtobufCIntRange zval_long__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor zval_long__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalLong",
  "ZvalLong",
  "ZvalLong",
  "",
  sizeof(ZvalLong),
  1,
  zval_long__field_descriptors,
  zval_long__field_indices_by_name,
  1,  zval_long__number_ranges,
  (ProtobufCMessageInit) zval_long__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zval_double__field_descriptors[1] =
{
  {
    "dval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(ZvalDouble, dval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zval_double__field_indices_by_name[] = {
  0,   /* field[0] = dval */
};
static const ProtobufCIntRange zval_double__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor zval_double__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalDouble",
  "ZvalDouble",
  "ZvalDouble",
  "",
  sizeof(ZvalDouble),
  1,
  zval_double__field_descriptors,
  zval_double__field_indices_by_name,
  1,  zval_double__number_ranges,
  (ProtobufCMessageInit) zval_double__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zval_string__field_descriptors[1] =
{
  {
    "str",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ZvalString, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zval_string__field_indices_by_name[] = {
  0,   /* field[0] = str */
};
static const ProtobufCIntRange zval_string__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor zval_string__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalString",
  "ZvalString",
  "ZvalString",
  "",
  sizeof(ZvalString),
  1,
  zval_string__field_descriptors,
  zval_string__field_indices_by_name,
  1,  zval_string__number_ranges,
  (ProtobufCMessageInit) zval_string__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define zval_array__field_descriptors NULL
#define zval_array__field_indices_by_name NULL
#define zval_array__number_ranges NULL
const ProtobufCMessageDescriptor zval_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalArray",
  "ZvalArray",
  "ZvalArray",
  "",
  sizeof(ZvalArray),
  0,
  zval_array__field_descriptors,
  zval_array__field_indices_by_name,
  0,  zval_array__number_ranges,
  (ProtobufCMessageInit) zval_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define zval_object__field_descriptors NULL
#define zval_object__field_indices_by_name NULL
#define zval_object__number_ranges NULL
const ProtobufCMessageDescriptor zval_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalObject",
  "ZvalObject",
  "ZvalObject",
  "",
  sizeof(ZvalObject),
  0,
  zval_object__field_descriptors,
  zval_object__field_indices_by_name,
  0,  zval_object__number_ranges,
  (ProtobufCMessageInit) zval_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zval_bool__field_descriptors[1] =
{
  {
    "bval",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ZvalBool, bval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zval_bool__field_indices_by_name[] = {
  0,   /* field[0] = bval */
};
static const ProtobufCIntRange zval_bool__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor zval_bool__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalBool",
  "ZvalBool",
  "ZvalBool",
  "",
  sizeof(ZvalBool),
  1,
  zval_bool__field_descriptors,
  zval_bool__field_indices_by_name,
  1,  zval_bool__number_ranges,
  (ProtobufCMessageInit) zval_bool__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define zval_resource__field_descriptors NULL
#define zval_resource__field_indices_by_name NULL
#define zval_resource__number_ranges NULL
const ProtobufCMessageDescriptor zval_resource__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalResource",
  "ZvalResource",
  "ZvalResource",
  "",
  sizeof(ZvalResource),
  0,
  zval_resource__field_descriptors,
  zval_resource__field_indices_by_name,
  0,  zval_resource__number_ranges,
  (ProtobufCMessageInit) zval_resource__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zval_const__field_descriptors[1] =
{
  {
    "str",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ZvalConst, str),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zval_const__field_indices_by_name[] = {
  0,   /* field[0] = str */
};
static const ProtobufCIntRange zval_const__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor zval_const__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalConst",
  "ZvalConst",
  "ZvalConst",
  "",
  sizeof(ZvalConst),
  1,
  zval_const__field_descriptors,
  zval_const__field_indices_by_name,
  1,  zval_const__number_ranges,
  (ProtobufCMessageInit) zval_const__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define zval_const_ast__field_descriptors NULL
#define zval_const_ast__field_indices_by_name NULL
#define zval_const_ast__number_ranges NULL
const ProtobufCMessageDescriptor zval_const_ast__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ZvalConstAst",
  "ZvalConstAst",
  "ZvalConstAst",
  "",
  sizeof(ZvalConstAst),
  0,
  zval_const_ast__field_descriptors,
  zval_const_ast__field_indices_by_name,
  0,  zval_const_ast__number_ranges,
  (ProtobufCMessageInit) zval_const_ast__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor zval__field_descriptors[11] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Zval, type),
    &zval_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "null",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, null),
    &zval_null__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, long_),
    &zval_long__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, double_),
    &zval_double__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, string),
    &zval_string__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, array),
    &zval_array__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, object),
    &zval_object__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, bool_),
    &zval_bool__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, resource),
    &zval_resource__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "const",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, const_),
    &zval_const__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "constAst",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Zval, val_case),
    offsetof(Zval, constast),
    &zval_const_ast__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned zval__field_indices_by_name[] = {
  5,   /* field[5] = array */
  7,   /* field[7] = bool */
  9,   /* field[9] = const */
  10,   /* field[10] = constAst */
  3,   /* field[3] = double */
  2,   /* field[2] = long */
  1,   /* field[1] = null */
  6,   /* field[6] = object */
  8,   /* field[8] = resource */
  4,   /* field[4] = string */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange zval__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor zval__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Zval",
  "Zval",
  "Zval",
  "",
  sizeof(Zval),
  11,
  zval__field_descriptors,
  zval__field_indices_by_name,
  1,  zval__number_ranges,
  (ProtobufCMessageInit) zval__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor znode__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Znode, type),
    &znode_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "zv",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Znode, zv),
    &zval__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned znode__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = zv */
};
static const ProtobufCIntRange znode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor znode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Znode",
  "Znode",
  "Znode",
  "",
  sizeof(Znode),
  2,
  znode__field_descriptors,
  znode__field_indices_by_name,
  1,  znode__number_ranges,
  (ProtobufCMessageInit) znode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor opcode_list__field_descriptors[1] =
{
  {
    "codes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpcodeList, n_codes),
    offsetof(OpcodeList, codes),
    &opcode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opcode_list__field_indices_by_name[] = {
  0,   /* field[0] = codes */
};
static const ProtobufCIntRange opcode_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor opcode_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpcodeList",
  "OpcodeList",
  "OpcodeList",
  "",
  sizeof(OpcodeList),
  1,
  opcode_list__field_descriptors,
  opcode_list__field_indices_by_name,
  1,  opcode_list__number_ranges,
  (ProtobufCMessageInit) opcode_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor opcode__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Opcode, name),
    &opcode_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op1",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Opcode, op1),
    &znode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op2",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Opcode, op2),
    &znode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opcode__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = op1 */
  2,   /* field[2] = op2 */
};
static const ProtobufCIntRange opcode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor opcode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Opcode",
  "Opcode",
  "Opcode",
  "",
  sizeof(Opcode),
  3,
  opcode__field_descriptors,
  opcode__field_indices_by_name,
  1,  opcode__number_ranges,
  (ProtobufCMessageInit) opcode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue opcode_name__enum_values_by_number[150] =
{
  { "NOP", "OPCODE_NAME__NOP", 0 },
  { "ADD", "OPCODE_NAME__ADD", 1 },
  { "SUB", "OPCODE_NAME__SUB", 2 },
  { "MUL", "OPCODE_NAME__MUL", 3 },
  { "DIV", "OPCODE_NAME__DIV", 4 },
  { "MOD", "OPCODE_NAME__MOD", 5 },
  { "SL", "OPCODE_NAME__SL", 6 },
  { "SR", "OPCODE_NAME__SR", 7 },
  { "CONCAT", "OPCODE_NAME__CONCAT", 8 },
  { "BW_OR", "OPCODE_NAME__BW_OR", 9 },
  { "BW_AND", "OPCODE_NAME__BW_AND", 10 },
  { "BW_XOR", "OPCODE_NAME__BW_XOR", 11 },
  { "BW_NOT", "OPCODE_NAME__BW_NOT", 12 },
  { "BOOL_NOT", "OPCODE_NAME__BOOL_NOT", 13 },
  { "BOOL_XOR", "OPCODE_NAME__BOOL_XOR", 14 },
  { "IS_IDENTICAL", "OPCODE_NAME__IS_IDENTICAL", 15 },
  { "IS_NOT_IDENTICAL", "OPCODE_NAME__IS_NOT_IDENTICAL", 16 },
  { "IS_EQUAL", "OPCODE_NAME__IS_EQUAL", 17 },
  { "IS_NOT_EQUAL", "OPCODE_NAME__IS_NOT_EQUAL", 18 },
  { "IS_SMALLER", "OPCODE_NAME__IS_SMALLER", 19 },
  { "IS_SMALLER_OR_EQUAL", "OPCODE_NAME__IS_SMALLER_OR_EQUAL", 20 },
  { "CAST", "OPCODE_NAME__CAST", 21 },
  { "QM_ASSIGN", "OPCODE_NAME__QM_ASSIGN", 22 },
  { "ASSIGN_ADD", "OPCODE_NAME__ASSIGN_ADD", 23 },
  { "ASSIGN_SUB", "OPCODE_NAME__ASSIGN_SUB", 24 },
  { "ASSIGN_MUL", "OPCODE_NAME__ASSIGN_MUL", 25 },
  { "ASSIGN_DIV", "OPCODE_NAME__ASSIGN_DIV", 26 },
  { "ASSIGN_MOD", "OPCODE_NAME__ASSIGN_MOD", 27 },
  { "ASSIGN_SL", "OPCODE_NAME__ASSIGN_SL", 28 },
  { "ASSIGN_SR", "OPCODE_NAME__ASSIGN_SR", 29 },
  { "ASSIGN_CONCAT", "OPCODE_NAME__ASSIGN_CONCAT", 30 },
  { "ASSIGN_BW_OR", "OPCODE_NAME__ASSIGN_BW_OR", 31 },
  { "ASSIGN_BW_AND", "OPCODE_NAME__ASSIGN_BW_AND", 32 },
  { "ASSIGN_BW_XOR", "OPCODE_NAME__ASSIGN_BW_XOR", 33 },
  { "PRE_INC", "OPCODE_NAME__PRE_INC", 34 },
  { "PRE_DEC", "OPCODE_NAME__PRE_DEC", 35 },
  { "POST_INC", "OPCODE_NAME__POST_INC", 36 },
  { "POST_DEC", "OPCODE_NAME__POST_DEC", 37 },
  { "ASSIGN", "OPCODE_NAME__ASSIGN", 38 },
  { "ASSIGN_REF", "OPCODE_NAME__ASSIGN_REF", 39 },
  { "ECHO", "OPCODE_NAME__ECHO", 40 },
  { "PRINT", "OPCODE_NAME__PRINT", 41 },
  { "JMP", "OPCODE_NAME__JMP", 42 },
  { "JMPZ", "OPCODE_NAME__JMPZ", 43 },
  { "JMPNZ", "OPCODE_NAME__JMPNZ", 44 },
  { "JMPZNZ", "OPCODE_NAME__JMPZNZ", 45 },
  { "JMPZ_EX", "OPCODE_NAME__JMPZ_EX", 46 },
  { "JMPNZ_EX", "OPCODE_NAME__JMPNZ_EX", 47 },
  { "CASE", "OPCODE_NAME__CASE", 48 },
  { "SWITCH_FREE", "OPCODE_NAME__SWITCH_FREE", 49 },
  { "BRK", "OPCODE_NAME__BRK", 50 },
  { "CONT", "OPCODE_NAME__CONT", 51 },
  { "BOOL", "OPCODE_NAME__BOOL", 52 },
  { "INIT_STRING", "OPCODE_NAME__INIT_STRING", 53 },
  { "ADD_CHAR", "OPCODE_NAME__ADD_CHAR", 54 },
  { "ADD_STRING", "OPCODE_NAME__ADD_STRING", 55 },
  { "ADD_VAR", "OPCODE_NAME__ADD_VAR", 56 },
  { "BEGIN_SILENCE", "OPCODE_NAME__BEGIN_SILENCE", 57 },
  { "END_SILENCE", "OPCODE_NAME__END_SILENCE", 58 },
  { "INIT_FCALL_BY_NAME", "OPCODE_NAME__INIT_FCALL_BY_NAME", 59 },
  { "DO_FCALL", "OPCODE_NAME__DO_FCALL", 60 },
  { "DO_FCALL_BY_NAME", "OPCODE_NAME__DO_FCALL_BY_NAME", 61 },
  { "RETURN", "OPCODE_NAME__RETURN", 62 },
  { "RECV", "OPCODE_NAME__RECV", 63 },
  { "RECV_INIT", "OPCODE_NAME__RECV_INIT", 64 },
  { "SEND_VAL", "OPCODE_NAME__SEND_VAL", 65 },
  { "SEND_VAR", "OPCODE_NAME__SEND_VAR", 66 },
  { "SEND_REF", "OPCODE_NAME__SEND_REF", 67 },
  { "NEW", "OPCODE_NAME__NEW", 68 },
  { "INIT_NS_FCALL_BY_NAME", "OPCODE_NAME__INIT_NS_FCALL_BY_NAME", 69 },
  { "FREE", "OPCODE_NAME__FREE", 70 },
  { "INIT_ARRAY", "OPCODE_NAME__INIT_ARRAY", 71 },
  { "ADD_ARRAY_ELEMENT", "OPCODE_NAME__ADD_ARRAY_ELEMENT", 72 },
  { "INCLUDE_OR_EVAL", "OPCODE_NAME__INCLUDE_OR_EVAL", 73 },
  { "UNSET_VAR", "OPCODE_NAME__UNSET_VAR", 74 },
  { "UNSET_DIM", "OPCODE_NAME__UNSET_DIM", 75 },
  { "UNSET_OBJ", "OPCODE_NAME__UNSET_OBJ", 76 },
  { "FE_RESET", "OPCODE_NAME__FE_RESET", 77 },
  { "FE_FETCH", "OPCODE_NAME__FE_FETCH", 78 },
  { "EXIT", "OPCODE_NAME__EXIT", 79 },
  { "FETCH_R", "OPCODE_NAME__FETCH_R", 80 },
  { "FETCH_DIM_R", "OPCODE_NAME__FETCH_DIM_R", 81 },
  { "FETCH_OBJ_R", "OPCODE_NAME__FETCH_OBJ_R", 82 },
  { "FETCH_W", "OPCODE_NAME__FETCH_W", 83 },
  { "FETCH_DIM_W", "OPCODE_NAME__FETCH_DIM_W", 84 },
  { "FETCH_OBJ_W", "OPCODE_NAME__FETCH_OBJ_W", 85 },
  { "FETCH_RW", "OPCODE_NAME__FETCH_RW", 86 },
  { "FETCH_DIM_RW", "OPCODE_NAME__FETCH_DIM_RW", 87 },
  { "FETCH_OBJ_RW", "OPCODE_NAME__FETCH_OBJ_RW", 88 },
  { "FETCH_IS", "OPCODE_NAME__FETCH_IS", 89 },
  { "FETCH_DIM_IS", "OPCODE_NAME__FETCH_DIM_IS", 90 },
  { "FETCH_OBJ_IS", "OPCODE_NAME__FETCH_OBJ_IS", 91 },
  { "FETCH_FUNC_ARG", "OPCODE_NAME__FETCH_FUNC_ARG", 92 },
  { "FETCH_DIM_FUNC_ARG", "OPCODE_NAME__FETCH_DIM_FUNC_ARG", 93 },
  { "FETCH_OBJ_FUNC_ARG", "OPCODE_NAME__FETCH_OBJ_FUNC_ARG", 94 },
  { "FETCH_UNSET", "OPCODE_NAME__FETCH_UNSET", 95 },
  { "FETCH_DIM_UNSET", "OPCODE_NAME__FETCH_DIM_UNSET", 96 },
  { "FETCH_OBJ_UNSET", "OPCODE_NAME__FETCH_OBJ_UNSET", 97 },
  { "FETCH_DIM_TMP_VAR", "OPCODE_NAME__FETCH_DIM_TMP_VAR", 98 },
  { "FETCH_CONSTANT", "OPCODE_NAME__FETCH_CONSTANT", 99 },
  { "GOTO", "OPCODE_NAME__GOTO", 100 },
  { "EXT_STMT", "OPCODE_NAME__EXT_STMT", 101 },
  { "EXT_FCALL_BEGIN", "OPCODE_NAME__EXT_FCALL_BEGIN", 102 },
  { "EXT_FCALL_END", "OPCODE_NAME__EXT_FCALL_END", 103 },
  { "EXT_NOP", "OPCODE_NAME__EXT_NOP", 104 },
  { "TICKS", "OPCODE_NAME__TICKS", 105 },
  { "SEND_VAR_NO_REF", "OPCODE_NAME__SEND_VAR_NO_REF", 106 },
  { "CATCH", "OPCODE_NAME__CATCH", 107 },
  { "THROW", "OPCODE_NAME__THROW", 108 },
  { "FETCH_CLASS", "OPCODE_NAME__FETCH_CLASS", 109 },
  { "CLONE", "OPCODE_NAME__CLONE", 110 },
  { "RETURN_BY_REF", "OPCODE_NAME__RETURN_BY_REF", 111 },
  { "INIT_METHOD_CALL", "OPCODE_NAME__INIT_METHOD_CALL", 112 },
  { "INIT_STATIC_METHOD_CALL", "OPCODE_NAME__INIT_STATIC_METHOD_CALL", 113 },
  { "ISSET_ISEMPTY_VAR", "OPCODE_NAME__ISSET_ISEMPTY_VAR", 114 },
  { "ISSET_ISEMPTY_DIM_OBJ", "OPCODE_NAME__ISSET_ISEMPTY_DIM_OBJ", 115 },
  { "PRE_INC_OBJ", "OPCODE_NAME__PRE_INC_OBJ", 132 },
  { "PRE_DEC_OBJ", "OPCODE_NAME__PRE_DEC_OBJ", 133 },
  { "POST_INC_OBJ", "OPCODE_NAME__POST_INC_OBJ", 134 },
  { "POST_DEC_OBJ", "OPCODE_NAME__POST_DEC_OBJ", 135 },
  { "ASSIGN_OBJ", "OPCODE_NAME__ASSIGN_OBJ", 136 },
  { "INSTANCEOF", "OPCODE_NAME__INSTANCEOF", 138 },
  { "DECLARE_CLASS", "OPCODE_NAME__DECLARE_CLASS", 139 },
  { "DECLARE_INHERITED_CLASS", "OPCODE_NAME__DECLARE_INHERITED_CLASS", 140 },
  { "DECLARE_FUNCTION", "OPCODE_NAME__DECLARE_FUNCTION", 141 },
  { "RAISE_ABSTRACT_ERROR", "OPCODE_NAME__RAISE_ABSTRACT_ERROR", 142 },
  { "DECLARE_CONST", "OPCODE_NAME__DECLARE_CONST", 143 },
  { "ADD_INTERFACE", "OPCODE_NAME__ADD_INTERFACE", 144 },
  { "DECLARE_INHERITED_CLASS_DELAYED", "OPCODE_NAME__DECLARE_INHERITED_CLASS_DELAYED", 145 },
  { "VERIFY_ABSTRACT_CLASS", "OPCODE_NAME__VERIFY_ABSTRACT_CLASS", 146 },
  { "ASSIGN_DIM", "OPCODE_NAME__ASSIGN_DIM", 147 },
  { "ISSET_ISEMPTY_PROP_OBJ", "OPCODE_NAME__ISSET_ISEMPTY_PROP_OBJ", 148 },
  { "HANDLE_EXCEPTION", "OPCODE_NAME__HANDLE_EXCEPTION", 149 },
  { "USER_OPCODE", "OPCODE_NAME__USER_OPCODE", 150 },
  { "JMP_SET", "OPCODE_NAME__JMP_SET", 152 },
  { "DECLARE_LAMBDA_FUNCTION", "OPCODE_NAME__DECLARE_LAMBDA_FUNCTION", 153 },
  { "ADD_TRAIT", "OPCODE_NAME__ADD_TRAIT", 154 },
  { "BIND_TRAITS", "OPCODE_NAME__BIND_TRAITS", 155 },
  { "SEPARATE", "OPCODE_NAME__SEPARATE", 156 },
  { "QM_ASSIGN_VAR", "OPCODE_NAME__QM_ASSIGN_VAR", 157 },
  { "JMP_SET_VAR", "OPCODE_NAME__JMP_SET_VAR", 158 },
  { "DISCARD_EXCEPTION", "OPCODE_NAME__DISCARD_EXCEPTION", 159 },
  { "YIELD", "OPCODE_NAME__YIELD", 160 },
  { "GENERATOR_RETURN", "OPCODE_NAME__GENERATOR_RETURN", 161 },
  { "FAST_CALL", "OPCODE_NAME__FAST_CALL", 162 },
  { "FAST_RET", "OPCODE_NAME__FAST_RET", 163 },
  { "RECV_VARIADIC", "OPCODE_NAME__RECV_VARIADIC", 164 },
  { "SEND_UNPACK", "OPCODE_NAME__SEND_UNPACK", 165 },
  { "POW", "OPCODE_NAME__POW", 166 },
  { "ASSIGN_POW", "OPCODE_NAME__ASSIGN_POW", 167 },
};
static const ProtobufCIntRange opcode_name__value_ranges[] = {
{0, 0},{132, 116},{138, 121},{152, 134},{0, 150}
};
static const ProtobufCEnumValueIndex opcode_name__enum_values_by_name[150] =
{
  { "ADD", 1 },
  { "ADD_ARRAY_ELEMENT", 72 },
  { "ADD_CHAR", 54 },
  { "ADD_INTERFACE", 127 },
  { "ADD_STRING", 55 },
  { "ADD_TRAIT", 136 },
  { "ADD_VAR", 56 },
  { "ASSIGN", 38 },
  { "ASSIGN_ADD", 23 },
  { "ASSIGN_BW_AND", 32 },
  { "ASSIGN_BW_OR", 31 },
  { "ASSIGN_BW_XOR", 33 },
  { "ASSIGN_CONCAT", 30 },
  { "ASSIGN_DIM", 130 },
  { "ASSIGN_DIV", 26 },
  { "ASSIGN_MOD", 27 },
  { "ASSIGN_MUL", 25 },
  { "ASSIGN_OBJ", 120 },
  { "ASSIGN_POW", 149 },
  { "ASSIGN_REF", 39 },
  { "ASSIGN_SL", 28 },
  { "ASSIGN_SR", 29 },
  { "ASSIGN_SUB", 24 },
  { "BEGIN_SILENCE", 57 },
  { "BIND_TRAITS", 137 },
  { "BOOL", 52 },
  { "BOOL_NOT", 13 },
  { "BOOL_XOR", 14 },
  { "BRK", 50 },
  { "BW_AND", 10 },
  { "BW_NOT", 12 },
  { "BW_OR", 9 },
  { "BW_XOR", 11 },
  { "CASE", 48 },
  { "CAST", 21 },
  { "CATCH", 107 },
  { "CLONE", 110 },
  { "CONCAT", 8 },
  { "CONT", 51 },
  { "DECLARE_CLASS", 122 },
  { "DECLARE_CONST", 126 },
  { "DECLARE_FUNCTION", 124 },
  { "DECLARE_INHERITED_CLASS", 123 },
  { "DECLARE_INHERITED_CLASS_DELAYED", 128 },
  { "DECLARE_LAMBDA_FUNCTION", 135 },
  { "DISCARD_EXCEPTION", 141 },
  { "DIV", 4 },
  { "DO_FCALL", 60 },
  { "DO_FCALL_BY_NAME", 61 },
  { "ECHO", 40 },
  { "END_SILENCE", 58 },
  { "EXIT", 79 },
  { "EXT_FCALL_BEGIN", 102 },
  { "EXT_FCALL_END", 103 },
  { "EXT_NOP", 104 },
  { "EXT_STMT", 101 },
  { "FAST_CALL", 144 },
  { "FAST_RET", 145 },
  { "FETCH_CLASS", 109 },
  { "FETCH_CONSTANT", 99 },
  { "FETCH_DIM_FUNC_ARG", 93 },
  { "FETCH_DIM_IS", 90 },
  { "FETCH_DIM_R", 81 },
  { "FETCH_DIM_RW", 87 },
  { "FETCH_DIM_TMP_VAR", 98 },
  { "FETCH_DIM_UNSET", 96 },
  { "FETCH_DIM_W", 84 },
  { "FETCH_FUNC_ARG", 92 },
  { "FETCH_IS", 89 },
  { "FETCH_OBJ_FUNC_ARG", 94 },
  { "FETCH_OBJ_IS", 91 },
  { "FETCH_OBJ_R", 82 },
  { "FETCH_OBJ_RW", 88 },
  { "FETCH_OBJ_UNSET", 97 },
  { "FETCH_OBJ_W", 85 },
  { "FETCH_R", 80 },
  { "FETCH_RW", 86 },
  { "FETCH_UNSET", 95 },
  { "FETCH_W", 83 },
  { "FE_FETCH", 78 },
  { "FE_RESET", 77 },
  { "FREE", 70 },
  { "GENERATOR_RETURN", 143 },
  { "GOTO", 100 },
  { "HANDLE_EXCEPTION", 132 },
  { "INCLUDE_OR_EVAL", 73 },
  { "INIT_ARRAY", 71 },
  { "INIT_FCALL_BY_NAME", 59 },
  { "INIT_METHOD_CALL", 112 },
  { "INIT_NS_FCALL_BY_NAME", 69 },
  { "INIT_STATIC_METHOD_CALL", 113 },
  { "INIT_STRING", 53 },
  { "INSTANCEOF", 121 },
  { "ISSET_ISEMPTY_DIM_OBJ", 115 },
  { "ISSET_ISEMPTY_PROP_OBJ", 131 },
  { "ISSET_ISEMPTY_VAR", 114 },
  { "IS_EQUAL", 17 },
  { "IS_IDENTICAL", 15 },
  { "IS_NOT_EQUAL", 18 },
  { "IS_NOT_IDENTICAL", 16 },
  { "IS_SMALLER", 19 },
  { "IS_SMALLER_OR_EQUAL", 20 },
  { "JMP", 42 },
  { "JMPNZ", 44 },
  { "JMPNZ_EX", 47 },
  { "JMPZ", 43 },
  { "JMPZNZ", 45 },
  { "JMPZ_EX", 46 },
  { "JMP_SET", 134 },
  { "JMP_SET_VAR", 140 },
  { "MOD", 5 },
  { "MUL", 3 },
  { "NEW", 68 },
  { "NOP", 0 },
  { "POST_DEC", 37 },
  { "POST_DEC_OBJ", 119 },
  { "POST_INC", 36 },
  { "POST_INC_OBJ", 118 },
  { "POW", 148 },
  { "PRE_DEC", 35 },
  { "PRE_DEC_OBJ", 117 },
  { "PRE_INC", 34 },
  { "PRE_INC_OBJ", 116 },
  { "PRINT", 41 },
  { "QM_ASSIGN", 22 },
  { "QM_ASSIGN_VAR", 139 },
  { "RAISE_ABSTRACT_ERROR", 125 },
  { "RECV", 63 },
  { "RECV_INIT", 64 },
  { "RECV_VARIADIC", 146 },
  { "RETURN", 62 },
  { "RETURN_BY_REF", 111 },
  { "SEND_REF", 67 },
  { "SEND_UNPACK", 147 },
  { "SEND_VAL", 65 },
  { "SEND_VAR", 66 },
  { "SEND_VAR_NO_REF", 106 },
  { "SEPARATE", 138 },
  { "SL", 6 },
  { "SR", 7 },
  { "SUB", 2 },
  { "SWITCH_FREE", 49 },
  { "THROW", 108 },
  { "TICKS", 105 },
  { "UNSET_DIM", 75 },
  { "UNSET_OBJ", 76 },
  { "UNSET_VAR", 74 },
  { "USER_OPCODE", 133 },
  { "VERIFY_ABSTRACT_CLASS", 129 },
  { "YIELD", 142 },
};
const ProtobufCEnumDescriptor opcode_name__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OpcodeName",
  "OpcodeName",
  "OpcodeName",
  "",
  150,
  opcode_name__enum_values_by_number,
  150,
  opcode_name__enum_values_by_name,
  4,
  opcode_name__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue znode_type__enum_values_by_number[9] =
{
  { "IS_CONST", "ZNODE_TYPE__IS_CONST", 0 },
  { "IS_TMP_VAR", "ZNODE_TYPE__IS_TMP_VAR", 1 },
  { "IS_VAR", "ZNODE_TYPE__IS_VAR", 2 },
  { "IS_UNUSED", "ZNODE_TYPE__IS_UNUSED", 3 },
  { "IS_CV", "ZNODE_TYPE__IS_CV", 4 },
  { "EXT_TYPE_UNUSED", "ZNODE_TYPE__EXT_TYPE_UNUSED", 5 },
  { "IS_OPNUM", "ZNODE_TYPE__IS_OPNUM", 6 },
  { "IS_OPLINE", "ZNODE_TYPE__IS_OPLINE", 7 },
  { "IS_CLASS", "ZNODE_TYPE__IS_CLASS", 8 },
};
static const ProtobufCIntRange znode_type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex znode_type__enum_values_by_name[9] =
{
  { "EXT_TYPE_UNUSED", 5 },
  { "IS_CLASS", 8 },
  { "IS_CONST", 0 },
  { "IS_CV", 4 },
  { "IS_OPLINE", 7 },
  { "IS_OPNUM", 6 },
  { "IS_TMP_VAR", 1 },
  { "IS_UNUSED", 3 },
  { "IS_VAR", 2 },
};
const ProtobufCEnumDescriptor znode_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ZnodeType",
  "ZnodeType",
  "ZnodeType",
  "",
  9,
  znode_type__enum_values_by_number,
  9,
  znode_type__enum_values_by_name,
  1,
  znode_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue zval_type__enum_values_by_number[10] =
{
  { "IS_NULL", "ZVAL_TYPE__IS_NULL", 0 },
  { "IS_LONG", "ZVAL_TYPE__IS_LONG", 1 },
  { "IS_DOUBLE", "ZVAL_TYPE__IS_DOUBLE", 2 },
  { "IS_STRING", "ZVAL_TYPE__IS_STRING", 3 },
  { "IS_ARRAY", "ZVAL_TYPE__IS_ARRAY", 4 },
  { "IS_OBJECT", "ZVAL_TYPE__IS_OBJECT", 5 },
  { "IS_RESOURCE", "ZVAL_TYPE__IS_RESOURCE", 6 },
  { "IS_CONSTANT", "ZVAL_TYPE__IS_CONSTANT", 7 },
  { "IS_CONSTANT_AST", "ZVAL_TYPE__IS_CONSTANT_AST", 8 },
  { "IS_BOOL", "ZVAL_TYPE__IS_BOOL", 9 },
};
static const ProtobufCIntRange zval_type__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex zval_type__enum_values_by_name[10] =
{
  { "IS_ARRAY", 4 },
  { "IS_BOOL", 9 },
  { "IS_CONSTANT", 7 },
  { "IS_CONSTANT_AST", 8 },
  { "IS_DOUBLE", 2 },
  { "IS_LONG", 1 },
  { "IS_NULL", 0 },
  { "IS_OBJECT", 5 },
  { "IS_RESOURCE", 6 },
  { "IS_STRING", 3 },
};
const ProtobufCEnumDescriptor zval_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ZvalType",
  "ZvalType",
  "ZvalType",
  "",
  10,
  zval_type__enum_values_by_number,
  10,
  zval_type__enum_values_by_name,
  1,
  zval_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
