/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/php_opcode.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/php_opcode.pb-c.h"
void   opcode_list__init
                     (OpcodeList         *message)
{
  static const OpcodeList init_value = OPCODE_LIST__INIT;
  *message = init_value;
}
size_t opcode_list__get_packed_size
                     (const OpcodeList *message)
{
  assert(message->base.descriptor == &opcode_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opcode_list__pack
                     (const OpcodeList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opcode_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opcode_list__pack_to_buffer
                     (const OpcodeList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opcode_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OpcodeList *
       opcode_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OpcodeList *)
     protobuf_c_message_unpack (&opcode_list__descriptor,
                                allocator, len, data);
}
void   opcode_list__free_unpacked
                     (OpcodeList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opcode_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   opcode__init
                     (Opcode         *message)
{
  static const Opcode init_value = OPCODE__INIT;
  *message = init_value;
}
size_t opcode__get_packed_size
                     (const Opcode *message)
{
  assert(message->base.descriptor == &opcode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opcode__pack
                     (const Opcode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opcode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opcode__pack_to_buffer
                     (const Opcode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opcode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Opcode *
       opcode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Opcode *)
     protobuf_c_message_unpack (&opcode__descriptor,
                                allocator, len, data);
}
void   opcode__free_unpacked
                     (Opcode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opcode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor opcode_list__field_descriptors[1] =
{
  {
    "codes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OpcodeList, n_codes),
    offsetof(OpcodeList, codes),
    &opcode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opcode_list__field_indices_by_name[] = {
  0,   /* field[0] = codes */
};
static const ProtobufCIntRange opcode_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor opcode_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OpcodeList",
  "OpcodeList",
  "OpcodeList",
  "",
  sizeof(OpcodeList),
  1,
  opcode_list__field_descriptors,
  opcode_list__field_indices_by_name,
  1,  opcode_list__number_ranges,
  (ProtobufCMessageInit) opcode_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor opcode__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Opcode, name),
    &opcode_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opcode__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange opcode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor opcode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Opcode",
  "Opcode",
  "Opcode",
  "",
  sizeof(Opcode),
  1,
  opcode__field_descriptors,
  opcode__field_indices_by_name,
  1,  opcode__number_ranges,
  (ProtobufCMessageInit) opcode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue opcode_name__enum_values_by_number[150] =
{
  { "NOP", "OPCODE_NAME__NOP", 0 },
  { "ADD", "OPCODE_NAME__ADD", 1 },
  { "SUB", "OPCODE_NAME__SUB", 2 },
  { "MUL", "OPCODE_NAME__MUL", 3 },
  { "DIV", "OPCODE_NAME__DIV", 4 },
  { "MOD", "OPCODE_NAME__MOD", 5 },
  { "SL", "OPCODE_NAME__SL", 6 },
  { "SR", "OPCODE_NAME__SR", 7 },
  { "CONCAT", "OPCODE_NAME__CONCAT", 8 },
  { "BW_OR", "OPCODE_NAME__BW_OR", 9 },
  { "BW_AND", "OPCODE_NAME__BW_AND", 10 },
  { "BW_XOR", "OPCODE_NAME__BW_XOR", 11 },
  { "BW_NOT", "OPCODE_NAME__BW_NOT", 12 },
  { "BOOL_NOT", "OPCODE_NAME__BOOL_NOT", 13 },
  { "BOOL_XOR", "OPCODE_NAME__BOOL_XOR", 14 },
  { "IS_IDENTICAL", "OPCODE_NAME__IS_IDENTICAL", 15 },
  { "IS_NOT_IDENTICAL", "OPCODE_NAME__IS_NOT_IDENTICAL", 16 },
  { "IS_EQUAL", "OPCODE_NAME__IS_EQUAL", 17 },
  { "IS_NOT_EQUAL", "OPCODE_NAME__IS_NOT_EQUAL", 18 },
  { "IS_SMALLER", "OPCODE_NAME__IS_SMALLER", 19 },
  { "IS_SMALLER_OR_EQUAL", "OPCODE_NAME__IS_SMALLER_OR_EQUAL", 20 },
  { "CAST", "OPCODE_NAME__CAST", 21 },
  { "QM_ASSIGN", "OPCODE_NAME__QM_ASSIGN", 22 },
  { "ASSIGN_ADD", "OPCODE_NAME__ASSIGN_ADD", 23 },
  { "ASSIGN_SUB", "OPCODE_NAME__ASSIGN_SUB", 24 },
  { "ASSIGN_MUL", "OPCODE_NAME__ASSIGN_MUL", 25 },
  { "ASSIGN_DIV", "OPCODE_NAME__ASSIGN_DIV", 26 },
  { "ASSIGN_MOD", "OPCODE_NAME__ASSIGN_MOD", 27 },
  { "ASSIGN_SL", "OPCODE_NAME__ASSIGN_SL", 28 },
  { "ASSIGN_SR", "OPCODE_NAME__ASSIGN_SR", 29 },
  { "ASSIGN_CONCAT", "OPCODE_NAME__ASSIGN_CONCAT", 30 },
  { "ASSIGN_BW_OR", "OPCODE_NAME__ASSIGN_BW_OR", 31 },
  { "ASSIGN_BW_AND", "OPCODE_NAME__ASSIGN_BW_AND", 32 },
  { "ASSIGN_BW_XOR", "OPCODE_NAME__ASSIGN_BW_XOR", 33 },
  { "PRE_INC", "OPCODE_NAME__PRE_INC", 34 },
  { "PRE_DEC", "OPCODE_NAME__PRE_DEC", 35 },
  { "POST_INC", "OPCODE_NAME__POST_INC", 36 },
  { "POST_DEC", "OPCODE_NAME__POST_DEC", 37 },
  { "ASSIGN", "OPCODE_NAME__ASSIGN", 38 },
  { "ASSIGN_REF", "OPCODE_NAME__ASSIGN_REF", 39 },
  { "ECHO", "OPCODE_NAME__ECHO", 40 },
  { "PRINT", "OPCODE_NAME__PRINT", 41 },
  { "JMP", "OPCODE_NAME__JMP", 42 },
  { "JMPZ", "OPCODE_NAME__JMPZ", 43 },
  { "JMPNZ", "OPCODE_NAME__JMPNZ", 44 },
  { "JMPZNZ", "OPCODE_NAME__JMPZNZ", 45 },
  { "JMPZ_EX", "OPCODE_NAME__JMPZ_EX", 46 },
  { "JMPNZ_EX", "OPCODE_NAME__JMPNZ_EX", 47 },
  { "CASE", "OPCODE_NAME__CASE", 48 },
  { "SWITCH_FREE", "OPCODE_NAME__SWITCH_FREE", 49 },
  { "BRK", "OPCODE_NAME__BRK", 50 },
  { "CONT", "OPCODE_NAME__CONT", 51 },
  { "BOOL", "OPCODE_NAME__BOOL", 52 },
  { "INIT_STRING", "OPCODE_NAME__INIT_STRING", 53 },
  { "ADD_CHAR", "OPCODE_NAME__ADD_CHAR", 54 },
  { "ADD_STRING", "OPCODE_NAME__ADD_STRING", 55 },
  { "ADD_VAR", "OPCODE_NAME__ADD_VAR", 56 },
  { "BEGIN_SILENCE", "OPCODE_NAME__BEGIN_SILENCE", 57 },
  { "END_SILENCE", "OPCODE_NAME__END_SILENCE", 58 },
  { "INIT_FCALL_BY_NAME", "OPCODE_NAME__INIT_FCALL_BY_NAME", 59 },
  { "DO_FCALL", "OPCODE_NAME__DO_FCALL", 60 },
  { "DO_FCALL_BY_NAME", "OPCODE_NAME__DO_FCALL_BY_NAME", 61 },
  { "RETURN", "OPCODE_NAME__RETURN", 62 },
  { "RECV", "OPCODE_NAME__RECV", 63 },
  { "RECV_INIT", "OPCODE_NAME__RECV_INIT", 64 },
  { "SEND_VAL", "OPCODE_NAME__SEND_VAL", 65 },
  { "SEND_VAR", "OPCODE_NAME__SEND_VAR", 66 },
  { "SEND_REF", "OPCODE_NAME__SEND_REF", 67 },
  { "NEW", "OPCODE_NAME__NEW", 68 },
  { "INIT_NS_FCALL_BY_NAME", "OPCODE_NAME__INIT_NS_FCALL_BY_NAME", 69 },
  { "FREE", "OPCODE_NAME__FREE", 70 },
  { "INIT_ARRAY", "OPCODE_NAME__INIT_ARRAY", 71 },
  { "ADD_ARRAY_ELEMENT", "OPCODE_NAME__ADD_ARRAY_ELEMENT", 72 },
  { "INCLUDE_OR_EVAL", "OPCODE_NAME__INCLUDE_OR_EVAL", 73 },
  { "UNSET_VAR", "OPCODE_NAME__UNSET_VAR", 74 },
  { "UNSET_DIM", "OPCODE_NAME__UNSET_DIM", 75 },
  { "UNSET_OBJ", "OPCODE_NAME__UNSET_OBJ", 76 },
  { "FE_RESET", "OPCODE_NAME__FE_RESET", 77 },
  { "FE_FETCH", "OPCODE_NAME__FE_FETCH", 78 },
  { "EXIT", "OPCODE_NAME__EXIT", 79 },
  { "FETCH_R", "OPCODE_NAME__FETCH_R", 80 },
  { "FETCH_DIM_R", "OPCODE_NAME__FETCH_DIM_R", 81 },
  { "FETCH_OBJ_R", "OPCODE_NAME__FETCH_OBJ_R", 82 },
  { "FETCH_W", "OPCODE_NAME__FETCH_W", 83 },
  { "FETCH_DIM_W", "OPCODE_NAME__FETCH_DIM_W", 84 },
  { "FETCH_OBJ_W", "OPCODE_NAME__FETCH_OBJ_W", 85 },
  { "FETCH_RW", "OPCODE_NAME__FETCH_RW", 86 },
  { "FETCH_DIM_RW", "OPCODE_NAME__FETCH_DIM_RW", 87 },
  { "FETCH_OBJ_RW", "OPCODE_NAME__FETCH_OBJ_RW", 88 },
  { "FETCH_IS", "OPCODE_NAME__FETCH_IS", 89 },
  { "FETCH_DIM_IS", "OPCODE_NAME__FETCH_DIM_IS", 90 },
  { "FETCH_OBJ_IS", "OPCODE_NAME__FETCH_OBJ_IS", 91 },
  { "FETCH_FUNC_ARG", "OPCODE_NAME__FETCH_FUNC_ARG", 92 },
  { "FETCH_DIM_FUNC_ARG", "OPCODE_NAME__FETCH_DIM_FUNC_ARG", 93 },
  { "FETCH_OBJ_FUNC_ARG", "OPCODE_NAME__FETCH_OBJ_FUNC_ARG", 94 },
  { "FETCH_UNSET", "OPCODE_NAME__FETCH_UNSET", 95 },
  { "FETCH_DIM_UNSET", "OPCODE_NAME__FETCH_DIM_UNSET", 96 },
  { "FETCH_OBJ_UNSET", "OPCODE_NAME__FETCH_OBJ_UNSET", 97 },
  { "FETCH_DIM_TMP_VAR", "OPCODE_NAME__FETCH_DIM_TMP_VAR", 98 },
  { "FETCH_CONSTANT", "OPCODE_NAME__FETCH_CONSTANT", 99 },
  { "GOTO", "OPCODE_NAME__GOTO", 100 },
  { "EXT_STMT", "OPCODE_NAME__EXT_STMT", 101 },
  { "EXT_FCALL_BEGIN", "OPCODE_NAME__EXT_FCALL_BEGIN", 102 },
  { "EXT_FCALL_END", "OPCODE_NAME__EXT_FCALL_END", 103 },
  { "EXT_NOP", "OPCODE_NAME__EXT_NOP", 104 },
  { "TICKS", "OPCODE_NAME__TICKS", 105 },
  { "SEND_VAR_NO_REF", "OPCODE_NAME__SEND_VAR_NO_REF", 106 },
  { "CATCH", "OPCODE_NAME__CATCH", 107 },
  { "THROW", "OPCODE_NAME__THROW", 108 },
  { "FETCH_CLASS", "OPCODE_NAME__FETCH_CLASS", 109 },
  { "CLONE", "OPCODE_NAME__CLONE", 110 },
  { "RETURN_BY_REF", "OPCODE_NAME__RETURN_BY_REF", 111 },
  { "INIT_METHOD_CALL", "OPCODE_NAME__INIT_METHOD_CALL", 112 },
  { "INIT_STATIC_METHOD_CALL", "OPCODE_NAME__INIT_STATIC_METHOD_CALL", 113 },
  { "ISSET_ISEMPTY_VAR", "OPCODE_NAME__ISSET_ISEMPTY_VAR", 114 },
  { "ISSET_ISEMPTY_DIM_OBJ", "OPCODE_NAME__ISSET_ISEMPTY_DIM_OBJ", 115 },
  { "PRE_INC_OBJ", "OPCODE_NAME__PRE_INC_OBJ", 132 },
  { "PRE_DEC_OBJ", "OPCODE_NAME__PRE_DEC_OBJ", 133 },
  { "POST_INC_OBJ", "OPCODE_NAME__POST_INC_OBJ", 134 },
  { "POST_DEC_OBJ", "OPCODE_NAME__POST_DEC_OBJ", 135 },
  { "ASSIGN_OBJ", "OPCODE_NAME__ASSIGN_OBJ", 136 },
  { "INSTANCEOF", "OPCODE_NAME__INSTANCEOF", 138 },
  { "DECLARE_CLASS", "OPCODE_NAME__DECLARE_CLASS", 139 },
  { "DECLARE_INHERITED_CLASS", "OPCODE_NAME__DECLARE_INHERITED_CLASS", 140 },
  { "DECLARE_FUNCTION", "OPCODE_NAME__DECLARE_FUNCTION", 141 },
  { "RAISE_ABSTRACT_ERROR", "OPCODE_NAME__RAISE_ABSTRACT_ERROR", 142 },
  { "DECLARE_CONST", "OPCODE_NAME__DECLARE_CONST", 143 },
  { "ADD_INTERFACE", "OPCODE_NAME__ADD_INTERFACE", 144 },
  { "DECLARE_INHERITED_CLASS_DELAYED", "OPCODE_NAME__DECLARE_INHERITED_CLASS_DELAYED", 145 },
  { "VERIFY_ABSTRACT_CLASS", "OPCODE_NAME__VERIFY_ABSTRACT_CLASS", 146 },
  { "ASSIGN_DIM", "OPCODE_NAME__ASSIGN_DIM", 147 },
  { "ISSET_ISEMPTY_PROP_OBJ", "OPCODE_NAME__ISSET_ISEMPTY_PROP_OBJ", 148 },
  { "HANDLE_EXCEPTION", "OPCODE_NAME__HANDLE_EXCEPTION", 149 },
  { "USER_OPCODE", "OPCODE_NAME__USER_OPCODE", 150 },
  { "JMP_SET", "OPCODE_NAME__JMP_SET", 152 },
  { "DECLARE_LAMBDA_FUNCTION", "OPCODE_NAME__DECLARE_LAMBDA_FUNCTION", 153 },
  { "ADD_TRAIT", "OPCODE_NAME__ADD_TRAIT", 154 },
  { "BIND_TRAITS", "OPCODE_NAME__BIND_TRAITS", 155 },
  { "SEPARATE", "OPCODE_NAME__SEPARATE", 156 },
  { "QM_ASSIGN_VAR", "OPCODE_NAME__QM_ASSIGN_VAR", 157 },
  { "JMP_SET_VAR", "OPCODE_NAME__JMP_SET_VAR", 158 },
  { "DISCARD_EXCEPTION", "OPCODE_NAME__DISCARD_EXCEPTION", 159 },
  { "YIELD", "OPCODE_NAME__YIELD", 160 },
  { "GENERATOR_RETURN", "OPCODE_NAME__GENERATOR_RETURN", 161 },
  { "FAST_CALL", "OPCODE_NAME__FAST_CALL", 162 },
  { "FAST_RET", "OPCODE_NAME__FAST_RET", 163 },
  { "RECV_VARIADIC", "OPCODE_NAME__RECV_VARIADIC", 164 },
  { "SEND_UNPACK", "OPCODE_NAME__SEND_UNPACK", 165 },
  { "POW", "OPCODE_NAME__POW", 166 },
  { "ASSIGN_POW", "OPCODE_NAME__ASSIGN_POW", 167 },
};
static const ProtobufCIntRange opcode_name__value_ranges[] = {
{0, 0},{132, 116},{138, 121},{152, 134},{0, 150}
};
static const ProtobufCEnumValueIndex opcode_name__enum_values_by_name[150] =
{
  { "ADD", 1 },
  { "ADD_ARRAY_ELEMENT", 72 },
  { "ADD_CHAR", 54 },
  { "ADD_INTERFACE", 127 },
  { "ADD_STRING", 55 },
  { "ADD_TRAIT", 136 },
  { "ADD_VAR", 56 },
  { "ASSIGN", 38 },
  { "ASSIGN_ADD", 23 },
  { "ASSIGN_BW_AND", 32 },
  { "ASSIGN_BW_OR", 31 },
  { "ASSIGN_BW_XOR", 33 },
  { "ASSIGN_CONCAT", 30 },
  { "ASSIGN_DIM", 130 },
  { "ASSIGN_DIV", 26 },
  { "ASSIGN_MOD", 27 },
  { "ASSIGN_MUL", 25 },
  { "ASSIGN_OBJ", 120 },
  { "ASSIGN_POW", 149 },
  { "ASSIGN_REF", 39 },
  { "ASSIGN_SL", 28 },
  { "ASSIGN_SR", 29 },
  { "ASSIGN_SUB", 24 },
  { "BEGIN_SILENCE", 57 },
  { "BIND_TRAITS", 137 },
  { "BOOL", 52 },
  { "BOOL_NOT", 13 },
  { "BOOL_XOR", 14 },
  { "BRK", 50 },
  { "BW_AND", 10 },
  { "BW_NOT", 12 },
  { "BW_OR", 9 },
  { "BW_XOR", 11 },
  { "CASE", 48 },
  { "CAST", 21 },
  { "CATCH", 107 },
  { "CLONE", 110 },
  { "CONCAT", 8 },
  { "CONT", 51 },
  { "DECLARE_CLASS", 122 },
  { "DECLARE_CONST", 126 },
  { "DECLARE_FUNCTION", 124 },
  { "DECLARE_INHERITED_CLASS", 123 },
  { "DECLARE_INHERITED_CLASS_DELAYED", 128 },
  { "DECLARE_LAMBDA_FUNCTION", 135 },
  { "DISCARD_EXCEPTION", 141 },
  { "DIV", 4 },
  { "DO_FCALL", 60 },
  { "DO_FCALL_BY_NAME", 61 },
  { "ECHO", 40 },
  { "END_SILENCE", 58 },
  { "EXIT", 79 },
  { "EXT_FCALL_BEGIN", 102 },
  { "EXT_FCALL_END", 103 },
  { "EXT_NOP", 104 },
  { "EXT_STMT", 101 },
  { "FAST_CALL", 144 },
  { "FAST_RET", 145 },
  { "FETCH_CLASS", 109 },
  { "FETCH_CONSTANT", 99 },
  { "FETCH_DIM_FUNC_ARG", 93 },
  { "FETCH_DIM_IS", 90 },
  { "FETCH_DIM_R", 81 },
  { "FETCH_DIM_RW", 87 },
  { "FETCH_DIM_TMP_VAR", 98 },
  { "FETCH_DIM_UNSET", 96 },
  { "FETCH_DIM_W", 84 },
  { "FETCH_FUNC_ARG", 92 },
  { "FETCH_IS", 89 },
  { "FETCH_OBJ_FUNC_ARG", 94 },
  { "FETCH_OBJ_IS", 91 },
  { "FETCH_OBJ_R", 82 },
  { "FETCH_OBJ_RW", 88 },
  { "FETCH_OBJ_UNSET", 97 },
  { "FETCH_OBJ_W", 85 },
  { "FETCH_R", 80 },
  { "FETCH_RW", 86 },
  { "FETCH_UNSET", 95 },
  { "FETCH_W", 83 },
  { "FE_FETCH", 78 },
  { "FE_RESET", 77 },
  { "FREE", 70 },
  { "GENERATOR_RETURN", 143 },
  { "GOTO", 100 },
  { "HANDLE_EXCEPTION", 132 },
  { "INCLUDE_OR_EVAL", 73 },
  { "INIT_ARRAY", 71 },
  { "INIT_FCALL_BY_NAME", 59 },
  { "INIT_METHOD_CALL", 112 },
  { "INIT_NS_FCALL_BY_NAME", 69 },
  { "INIT_STATIC_METHOD_CALL", 113 },
  { "INIT_STRING", 53 },
  { "INSTANCEOF", 121 },
  { "ISSET_ISEMPTY_DIM_OBJ", 115 },
  { "ISSET_ISEMPTY_PROP_OBJ", 131 },
  { "ISSET_ISEMPTY_VAR", 114 },
  { "IS_EQUAL", 17 },
  { "IS_IDENTICAL", 15 },
  { "IS_NOT_EQUAL", 18 },
  { "IS_NOT_IDENTICAL", 16 },
  { "IS_SMALLER", 19 },
  { "IS_SMALLER_OR_EQUAL", 20 },
  { "JMP", 42 },
  { "JMPNZ", 44 },
  { "JMPNZ_EX", 47 },
  { "JMPZ", 43 },
  { "JMPZNZ", 45 },
  { "JMPZ_EX", 46 },
  { "JMP_SET", 134 },
  { "JMP_SET_VAR", 140 },
  { "MOD", 5 },
  { "MUL", 3 },
  { "NEW", 68 },
  { "NOP", 0 },
  { "POST_DEC", 37 },
  { "POST_DEC_OBJ", 119 },
  { "POST_INC", 36 },
  { "POST_INC_OBJ", 118 },
  { "POW", 148 },
  { "PRE_DEC", 35 },
  { "PRE_DEC_OBJ", 117 },
  { "PRE_INC", 34 },
  { "PRE_INC_OBJ", 116 },
  { "PRINT", 41 },
  { "QM_ASSIGN", 22 },
  { "QM_ASSIGN_VAR", 139 },
  { "RAISE_ABSTRACT_ERROR", 125 },
  { "RECV", 63 },
  { "RECV_INIT", 64 },
  { "RECV_VARIADIC", 146 },
  { "RETURN", 62 },
  { "RETURN_BY_REF", 111 },
  { "SEND_REF", 67 },
  { "SEND_UNPACK", 147 },
  { "SEND_VAL", 65 },
  { "SEND_VAR", 66 },
  { "SEND_VAR_NO_REF", 106 },
  { "SEPARATE", 138 },
  { "SL", 6 },
  { "SR", 7 },
  { "SUB", 2 },
  { "SWITCH_FREE", 49 },
  { "THROW", 108 },
  { "TICKS", 105 },
  { "UNSET_DIM", 75 },
  { "UNSET_OBJ", 76 },
  { "UNSET_VAR", 74 },
  { "USER_OPCODE", 133 },
  { "VERIFY_ABSTRACT_CLASS", 129 },
  { "YIELD", 142 },
};
const ProtobufCEnumDescriptor opcode_name__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OpcodeName",
  "OpcodeName",
  "OpcodeName",
  "",
  150,
  opcode_name__enum_values_by_number,
  150,
  opcode_name__enum_values_by_name,
  4,
  opcode_name__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
